//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUTPRO_Web.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Review_ID { get; set; }
        public int Tutor_ID { get; set; }
        public string StarRating { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public string Message { get; set; }
    
        public virtual Tutor Tutor { get; set; }
    }
}
