//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUTPRO_Web.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversityStudent
    {
        public int University_Account { get; set; }
        public int Student_ID { get; set; }
        public int Degree_ID { get; set; }
    
        public virtual Degree Degree { get; set; }
        public virtual Student Student { get; set; }
    }
}
